/**
 * Build the browser half of @dsh-plugins/memory into the artifact the dsh
 * client module system consumes: a classic script whose only execution-time
 * side effect is REGISTERING its CJS factory (`window.__ModuleLoader__.load`),
 * per @deepseek-ai/dsh-client-modules' lazy-CJS contract. The plugin body
 * (and the CSS-injection side effect) run later, at materialization.
 *
 * Peer dependencies (react) stay external: the shell's module table resolves
 * them through its platform seed words, exactly like the shipped client
 * packages' bundles.
 */
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const outPath = resolve(root, 'dist/client.js');

const result = await build({
  entryPoints: [resolve(root, 'src/client/index.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: ['es2020'],
  external: ['react', '@deepseek-ai/*'],
  minify: true,
  sourcemap: true,
  write: false,
  outfile: outPath,
  logLevel: 'info'
});

const body = result.outputFiles.find((f) => f.path === outPath).text.replace(/\n*\/\/# sourceMappingURL=.*\n?/g, '\n');
const map = result.outputFiles.find((f) => f.path === `${outPath}.map`);
const bundle = `/*! @dsh-plugins/memory client — generated by scripts/build-client.mjs */
(function () {
'use strict';
var factory = function (require, module, exports) {
${body}
};
var globalTarget = typeof window !== 'undefined' ? window : globalThis;
globalTarget.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: factory });
})();
//# sourceMappingURL=client.js.map
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, bundle);
if (map) {
  writeFileSync(resolve(root, 'dist/client.js.map'), map.text);
}
console.log(`client bundle: ${outPath} (${bundle.length} bytes)`);
